#!/bin/zsh -feu

set -x

# Hardcoded input:
# canibalize files from this tree:
src_repo=~/git/windows/Windows-driver-samples/
# but it's a git, so this commit:
COMMIT="base"

# we will create git commits on this branch: of the current git repo:
target_branch="win-import"
target=$(git rev-parse --show-toplevel)/windows/
# on target,
# I can have a second root!

# fixme: drop this:
# git -C $target checkout $target_branch

git -C $src_repo checkout $COMMIT
sha=$(git -C $src_repo rev-parse $COMMIT)


cd $src_repo/input/kbfiltr/
files=(
    README.md
    kbfiltr.sln
    sys/kbfiltr.c
    sys/kbfiltr.h
    sys/kbfiltr.inx
    sys/kbfiltr.rc
    sys/kbfiltr.vcxproj
    sys/kbfiltr.vcxproj.Filters
    sys/public.h
    sys/rawpdo.c
    # user-space app:
    exe/kbftest.c
    exe/kbftest.vcxproj
    exe/kbftest.vcxproj.Filters
    )

if false;
then
    foreach file ($files) {
        cp --verbose $file  $target/$file
    }
else
    cp --parents --verbose --update  --target-directory $target  $files

    for file ($files) {
        dos2unix $target/$file
    }

    cd $target
    git add $files
    git commit -m "import at $sha"
fi


# git commit -m "Import from "
